### ISSUE TITLE
problem with sbt

### ISSUE THREAD

**Issue by Gia79** [akamali/mitsubishi_heatpump_emulator#1]
sorry, i tried to use your emulator . i downloaded SBT but i can't understand This step " then in the root of the project run `sbt run SerialHeatPump.main`."
once downloaded sbt what files and where should I copy them? i downloaded sbt1.9.
I would be very grateful for some help. You have come up with a brilliant idea

**Comment by akamali** [comment]
Let's say you have downloaded sbt into `C:\sbt` and you have cloned this project to `C:\emulator`. Then you go to `C:\emulator` and run `C:\sbt\sbt.bat run SerialHeatPump.main`. Alternative you put sbt into your path.

**Comment by Gia79** [comment]
Thanks, it works😀
