### ISSUE TITLE
problem with serial connection

### ISSUE THREAD

**Issue by Gia79** [akamali/mitsubishi_heatpump_emulator#2]
Sorry ,but i have this problem.
Can You help me?
i am using a nodemcu v3 and the example  Hp_ctrl_esp8266  of swiCago.
The serial interface is a Cp2102 serial uart control
![Immagine 2023-06-28 210121](https://github.com/akamali/mitsubishi_heatpump_emulator/assets/134832033/a2b82d82-db4b-430f-9752-8e12b6536a2f)

**Comment by Gia79** [comment]
Sorry, I have changed the interface, now I have used a ft232 and esp01 programmed with swicago firmware, but I have the same problem of connection. Can you help me?

**Comment by akamali** [comment]
There is a support chat [here ](https://app.gitter.im/#/room/#Mitsubishi-Heat-Pump_Lobby:gitter.im) where you might find similar problems and ask for help.
